import type { HomeContent } from "./types";

export const de: HomeContent = {
  h1: "Wordle: Das ultimative Wort-Ratespiel",
  intro:
    "Wordle ist ein tägliches Worträtsel, bei dem du sechs Versuche hast, ein verstecktes Wort aus fünf Buchstaben zu erraten. Nach jedem Versuch ändern die Kacheln ihre Farbe und zeigen, wie nah du dran bist: Grün für einen Buchstaben an der richtigen Stelle, Gelb für einen Buchstaben, der im Wort steht aber an anderer Stelle, und Grau für einen Buchstaben, der gar nicht im Wort vorkommt. Jeden Tag erscheint ein brandneues Rätsel und alle spielen dasselbe Wort.",
  howToTitle: "So spielst du Wordle",
  howToSteps: [
    { title: "Gib deinen ersten Versuch ein", body: "Tippe ein beliebiges gültiges Wort mit fünf Buchstaben und drücke Enter. Raten kostet nichts, also nutze den ersten Versuch, um häufige Buchstaben zu testen." },
    { title: "Lies die Farben", body: "Grün heißt, der Buchstabe ist korrekt und an der richtigen Stelle. Gelb heißt, er kommt im Wort vor, aber an anderer Stelle. Grau heißt, er kommt nicht im Wort vor." },
    { title: "Verfeinere den nächsten Versuch", body: "Behalte die grünen Buchstaben an ihrem Platz, verschiebe die gelben woanders hin und meide die grauen beim nächsten Versuch komplett." },
    { title: "Löse es in sechs Versuchen", body: "Du hast sechs Versuche, das Wort zu finden. Jeder Versuch grenzt die Möglichkeiten ein, also überlege gut, bevor du bestätigst." },
    { title: "Komm morgen wieder", body: "Das tägliche Wort wechselt um Mitternacht. Teile dein Farbraster mit Freunden und vergleicht eure Anzahl Versuche, ohne die Lösung zu verraten." },
  ],
  moreGamesTitle: "Weitere Wortspiele",
  moreGames: [
    { path: "/unlimited", name: "Unbegrenzt", thumb: "wordle", blurb: "Spiele so viele Zufallsrätsel, wie du willst, ohne Tagesgrenze." },
    { path: "/dordle", name: "Dordle", thumb: "dordle", blurb: "Löse zwei Felder parallel in sieben Versuchen." },
    { path: "/quordle", name: "Quordle", thumb: "quordle", blurb: "Löse vier Felder parallel in neun Versuchen." },
    { path: "/octordle", name: "Octordle", thumb: "octordle", blurb: "Löse acht Felder parallel in dreizehn Versuchen." },
    { path: "/sedecordle", name: "Sedecordle", thumb: "sedecordle", blurb: "Löse sechzehn Felder gleichzeitig in einundzwanzig Versuchen." },
    { path: "/spellbee", name: "SpellBee", thumb: "spellbee", blurb: "Bilde so viele Wörter wie möglich aus sieben Buchstaben." },
    { path: "/connect", name: "Verbinden", thumb: "connect", blurb: "Sortiere sechzehn Wörter in vier versteckte Vierergruppen." },
    { path: "/squares", name: "Quadrate", thumb: "squares", blurb: "Verbinde benachbarte Buchstaben in einem 4×4-Raster zu Wörtern." },
    { path: "/custom", name: "Eigenes Wort", thumb: "custom", blurb: "Verstecke ein eigenes Wort und teile den Link mit Freunden." },
    { path: "/multiplayer", name: "Mehrspieler", thumb: "multiplayer", blurb: "Tritt in einem privaten Raum in Echtzeit gegen einen Freund an." },
    { path: "/solver", name: "Löser", thumb: "solver", blurb: "Steckst du fest? Gib deine Hinweise ein und sieh alle möglichen Antworten." },
    { path: "/archive", name: "Archiv", thumb: "archive", blurb: "Hol verpasste tägliche Rätsel nach." },
  ],
  languageTitle: "Sprache wählen",
  languageIntro:
    "Wordle gibt es in vielen Sprachen. Jede Version nutzt ihr eigenes Wörterbuch und Tastaturlayout, sodass du in der Sprache spielen kannst, die du am besten beherrschst.",
  tipsTitle: "Tipps zum Wordle-Spielen",
  tips: [
    { title: "Beginne mit einem starken Wort", body: "Wähle ein Wort, das mehrere häufige Buchstaben abdeckt: eine ausgewogene Mischung aus Vokalen und häufigen Konsonanten liefert die meiste Information aus einem Versuch." },
    { title: "Achte auf die Position", body: "Eine gelbe Kachel sagt dir, dass der Buchstabe im Wort steht, aber nicht da, wo du ihn platziert hast. Probiere beim nächsten Versuch eine andere Stelle." },
    { title: "Nutze keine grauen Buchstaben erneut", body: "Sobald ein Buchstabe grau ist, hast du ihn komplett ausgeschlossen. Einen Versuch mit ihm zu verbrennen ist verschenkte Zeit." },
    { title: "Suche nach Buchstabenmustern", body: "Sprachen haben viele wiederkehrende Formen wie typische Endungen und Vorsilben. Sie zu erkennen schließt oft die letzten Kacheln ein." },
    { title: "Setze auf vertraute Wörter", body: "Wenn mehrere Buchstaben passen, nimm Alltagswörter. Die Lösung ist fast nie obskur." },
    { title: "Schließe früh Gruppen aus", body: "Nutze den zweiten oder dritten Versuch, um neue Buchstaben zu testen, selbst wenn du damit nicht gewinnen kannst. Fünf weitere ausgeschlossen sind oft mehr wert." },
    { title: "Bleib ruhig und denk nach", body: "Es gibt keine Uhr. Werde bei den letzten beiden Versuchen langsamer und gehe die verbleibenden Kandidaten im Kopf durch." },
    { title: "Den Löser sparsam nutzen", body: "Der Löser ist nützlich zum Lernen, aber täglich raubt er den Spaß. Verwende ihn nur, wenn du wirklich feststeckst." },
    { title: "Spiele regelmäßig", body: "Je mehr Rätsel du spielst, desto vertrauter werden die Muster. Eine kurze tägliche Runde reicht, um in Übung zu bleiben." },
  ],
  faqTitle: "Häufig gestellte Fragen",
  faq: [
    { q: "Wie viele Versuche habe ich?", a: "Du hast sechs Versuche, das versteckte Wort zu finden. Jeder Versuch muss ein echtes Wort mit der richtigen Länge sein." },
    { q: "Was bedeuten die Farben?", a: "Grün markiert einen Buchstaben an der richtigen Position, Gelb einen Buchstaben, der im Wort vorkommt aber an anderer Stelle, und Grau einen Buchstaben, der nicht im Wort vorkommt." },
    { q: "Gibt es jeden Tag ein neues Wort?", a: "Ja. Das tägliche Rätsel ist für alle gleich und wechselt um Mitternacht. Wer mehr möchte, kann den Unbegrenzt-Modus nutzen, der nie ausgeht." },
    { q: "Kann ich öfter als einmal am Tag spielen?", a: "Das tägliche Wort ist einmal pro Tag, aber im Unbegrenzt-Modus, in den Längen-Varianten und in eigenen Spielen kannst du so oft spielen, wie du willst." },
    { q: "Können sich Buchstaben in der Lösung wiederholen?", a: "Ja. Das versteckte Wort kann denselben Buchstaben mehrfach enthalten, schließe doppelte Buchstaben also nicht aus." },
    { q: "Was ist der schwere Modus?", a: "Im schweren Modus müssen alle bisher gezeigten Hinweise in jedem späteren Versuch verwendet werden: Grüne bleiben an Ort und Stelle, Gelbe müssen irgendwo auftauchen." },
    { q: "Wie teile ich mein Ergebnis?", a: "Wenn du fertig bist, kopiert die Teilen-Schaltfläche ein spoilerfreies Farbraster, das zeigt, wie viele Versuche du gebraucht hast." },
    { q: "Kann ich in anderen Sprachen spielen?", a: "Ja. Über die Sprachauswahl wechselst du die Oberfläche und die Wortliste zu einer der unterstützten Sprachen." },
  ],
  advantagesTitle: "Vorteile von Wordle",
  advantages: [
    { icon: "book", title: "Erweitert den Wortschatz", body: "Täglich neue Wörter zu raten und zu lesen ist eine angenehme Art, Rechtschreibung und Wortwissen zu verbessern." },
    { icon: "lightning", title: "Kostenlos und sofort", body: "Kein Download, keine Anmeldung, keine Zahlung. Seite öffnen und losspielen." },
    { icon: "puzzle", title: "Schärft das logische Denken", body: "Jeder Hinweis schränkt die Möglichkeiten ein. Das Lösen ist eine kleine tägliche Übung in Deduktion." },
    { icon: "brain", title: "Ein sanftes Gehirntraining", body: "Ein paar konzentrierte Minuten Mustererkennung halten den Kopf aktiv, ohne wie Arbeit zu wirken." },
    { icon: "clock", title: "Kein Zeitdruck", body: "Es gibt keinen Timer. Nimm dir so viel Zeit, wie du brauchst." },
    { icon: "share", title: "Macht Spaß zu teilen", body: "Vergleiche dein Farbraster mit Freunden und Familie und schaut, wer es mit den wenigsten Versuchen geschafft hat." },
  ],
  ratingTitle: "Bewerte das Spiel",
  ratingValue: 4.3,
  ratingCount: 3847,
};
