import type { HomeContent } from "./types";

export const es: HomeContent = {
  h1: "Wordle – El juego definitivo de adivinar palabras",
  intro:
    "Wordle es un puzle diario en el que tienes seis intentos para adivinar una palabra oculta de cinco letras. Después de cada intento, las casillas cambian de color para mostrarte lo cerca que estás: verde si la letra está en la posición correcta, amarillo si la letra está en la palabra pero en otro lugar, y gris si la letra no está en la palabra. Cada día se publica un puzle nuevo y todos jugamos la misma palabra.",
  howToTitle: "Cómo jugar a Wordle",
  howToSteps: [
    { title: "Escribe tu primer intento", body: "Introduce cualquier palabra válida de cinco letras y pulsa Intro. No hay penalización por adivinar, así que aprovecha el primer intento para probar letras comunes." },
    { title: "Lee los colores", body: "El verde indica que la letra es correcta y está en la posición correcta. El amarillo significa que la letra está en la palabra pero en otra posición. El gris significa que la letra no está en la palabra." },
    { title: "Refina el siguiente intento", body: "Mantén las letras verdes en su sitio, prueba las amarillas en otra posición y descarta por completo las grises en el siguiente intento." },
    { title: "Resuélvelo en seis intentos", body: "Tienes seis oportunidades para encontrar la palabra oculta. Cada intento reduce las posibilidades, así que piénsalo antes de confirmar." },
    { title: "Vuelve mañana", body: "La palabra diaria se reinicia a medianoche. Comparte tu cuadrícula de colores con amigos y comparad cuántos intentos os ha costado sin revelar la respuesta." },
  ],
  moreGamesTitle: "Más juegos de palabras",
  moreGames: [
    { path: "/unlimited", name: "Ilimitado", thumb: "wordle", blurb: "Juega tantos puzles aleatorios como quieras, sin límite diario." },
    { path: "/dordle", name: "Dordle", thumb: "dordle", blurb: "Resuelve dos tableros en paralelo en siete intentos." },
    { path: "/quordle", name: "Quordle", thumb: "quordle", blurb: "Resuelve cuatro tableros en paralelo en nueve intentos." },
    { path: "/octordle", name: "Octordle", thumb: "octordle", blurb: "Resuelve ocho tableros en paralelo en trece intentos." },
    { path: "/sedecordle", name: "Sedecordle", thumb: "sedecordle", blurb: "Resuelve dieciséis tableros a la vez en veintiún intentos." },
    { path: "/spellbee", name: "SpellBee", thumb: "spellbee", blurb: "Forma todas las palabras que puedas con siete letras." },
    { path: "/connect", name: "Conectar", thumb: "connect", blurb: "Agrupa dieciséis palabras en cuatro grupos ocultos de cuatro." },
    { path: "/squares", name: "Cuadrados", thumb: "squares", blurb: "Une letras adyacentes en una cuadrícula 4×4 para formar palabras." },
    { path: "/custom", name: "Palabra Personalizada", thumb: "custom", blurb: "Esconde tu propia palabra y comparte el enlace con amigos." },
    { path: "/multiplayer", name: "Multijugador", thumb: "multiplayer", blurb: "Compite contra un amigo en tiempo real en una sala privada." },
    { path: "/solver", name: "Solucionador", thumb: "solver", blurb: "¿Atascado? Introduce tus pistas y mira todas las respuestas posibles." },
    { path: "/archive", name: "Archivo", thumb: "archive", blurb: "Vuelve a jugar puzles diarios pasados que te hayas saltado." },
  ],
  languageTitle: "Elige un idioma",
  languageIntro:
    "Wordle está disponible en muchos idiomas. Cada versión usa su propio diccionario y disposición de teclado, así que puedes jugar en el que mejor conozcas.",
  tipsTitle: "Consejos para jugar a Wordle",
  tips: [
    { title: "Empieza con una palabra fuerte", body: "Elige una palabra que cubra varias letras comunes: una mezcla equilibrada de vocales y consonantes frecuentes te dará la máxima información en un solo intento." },
    { title: "Presta atención a la posición", body: "Una casilla amarilla te dice que la letra está en la palabra, pero no donde la colocaste. Prueba en otra posición la próxima vez y lleva la cuenta mental." },
    { title: "No reutilices letras grises", body: "Cuando una letra es gris la has descartado por completo. Gastar un intento en una palabra que la contiene es perder un turno." },
    { title: "Busca patrones de letras", body: "El idioma tiene muchas formas recurrentes — terminaciones comunes, prefijos habituales — y reconocerlas suele fijar las últimas casillas." },
    { title: "Prueba palabras familiares", body: "Cuando varias letras encajan, decántate por palabras de uso diario. La respuesta casi nunca es rara." },
    { title: "Descarta grupos de letras pronto", body: "Usa el segundo o tercer intento para probar letras nuevas aunque no puedas ganar la ronda. Eliminar cinco letras más suele compensar." },
    { title: "Mantén la calma y piensa", body: "No hay reloj. Tómate tu tiempo en los dos últimos intentos y repasa los candidatos restantes antes de confirmar." },
    { title: "Usa el solucionador con moderación", body: "Está bien para aprender, pero usarlo cada día le quita la gracia. Resérvalo para cuando estés realmente atascado." },
    { title: "Practica con regularidad", body: "Cuantos más puzles juegues, más familiares te resultarán los patrones. Una ronda corta al día basta para mantenerte en forma." },
  ],
  faqTitle: "Preguntas frecuentes",
  faq: [
    { q: "¿Cuántos intentos tengo?", a: "Tienes seis intentos para encontrar la palabra oculta. Cada intento debe ser una palabra real de la longitud correcta." },
    { q: "¿Qué significan los colores?", a: "El verde marca una letra en la posición correcta, el amarillo una letra que está en la palabra pero en otra posición, y el gris una letra que no está en la palabra." },
    { q: "¿Hay una palabra nueva cada día?", a: "Sí. El puzle diario es el mismo para todos y cambia a medianoche. Si quieres más, el modo Ilimitado no se acaba nunca." },
    { q: "¿Puedo jugar más de una vez al día?", a: "La palabra diaria es una por día, pero los modos Ilimitado, las variantes por longitud y los juegos personalizados te dejan jugar cuanto quieras." },
    { q: "¿Pueden repetirse letras en la respuesta?", a: "Sí. La palabra oculta puede contener la misma letra varias veces, así que no descartes las letras dobles." },
    { q: "¿Qué es el Modo Difícil?", a: "En el Modo Difícil toda pista revelada debe usarse en los siguientes intentos: las verdes se quedan y las amarillas tienen que aparecer." },
    { q: "¿Cómo comparto mi resultado?", a: "Cuando termines, el botón de compartir copia una cuadrícula de colores sin spoilers que muestra cuántos intentos te costó." },
    { q: "¿Puedo jugar en otros idiomas?", a: "Sí. Usa el selector de idioma para cambiar la interfaz y la lista de palabras a uno de los idiomas disponibles." },
  ],
  advantagesTitle: "Ventajas del juego Wordle",
  advantages: [
    { icon: "book", title: "Amplía tu vocabulario", body: "Adivinar y leer palabras nuevas cada día es una forma sencilla de mejorar la ortografía y el léxico." },
    { icon: "lightning", title: "Gratis y al instante", body: "Sin descargas, sin registro, sin pagos. Abre la página y empieza a jugar." },
    { icon: "puzzle", title: "Agudiza la lógica", body: "Cada pista reduce el espacio de posibilidades. Resolverlo es un pequeño ejercicio diario de deducción." },
    { icon: "brain", title: "Un entrenamiento mental suave", body: "Unos minutos de búsqueda de patrones mantienen la mente activa sin parecer un esfuerzo." },
    { icon: "clock", title: "Sin prisas", body: "No hay cronómetro. Tómate todo el tiempo que necesites para pensar cada intento." },
    { icon: "share", title: "Divertido de compartir", body: "Compara tu cuadrícula con familia y amigos y mira quién lo resolvió en menos intentos." },
  ],
  ratingTitle: "Valora el juego",
  ratingValue: 4.3,
  ratingCount: 3847,
};
