import type { HomeContent } from "./types";

export const fr: HomeContent = {
  h1: "Wordle: Le jeu ultime de devinette de mots",
  intro:
    "Wordle est un puzzle quotidien dans lequel vous avez six essais pour deviner un mot caché de cinq lettres. Après chaque essai, les cases changent de couleur pour indiquer votre proximité : vert pour une lettre à la bonne place, jaune pour une lettre présente dans le mot mais à un autre endroit, et gris pour une lettre absente du mot. Une nouvelle énigme est publiée chaque jour, et tout le monde joue le même mot.",
  howToTitle: "Comment jouer à Wordle",
  howToSteps: [
    { title: "Tapez votre premier essai", body: "Saisissez n'importe quel mot valide de cinq lettres et appuyez sur Entrée. Il n'y a aucune pénalité, alors utilisez votre premier essai pour tester des lettres courantes." },
    { title: "Lisez les couleurs", body: "Vert signifie que la lettre est correcte et bien placée. Jaune signifie qu'elle est dans le mot mais ailleurs. Gris signifie qu'elle n'y est pas du tout." },
    { title: "Affinez votre prochain essai", body: "Gardez les lettres vertes à leur place, déplacez les jaunes ailleurs et évitez complètement les grises au prochain essai." },
    { title: "Trouvez-le en six essais", body: "Vous avez six essais pour trouver le mot caché. Chaque essai réduit les possibilités, alors réfléchissez avant de valider." },
    { title: "Revenez demain", body: "Le mot du jour change à minuit. Partagez votre grille de couleurs avec vos amis et comparez vos résultats sans dévoiler la réponse." },
  ],
  moreGamesTitle: "Plus de jeux de mots",
  moreGames: [
    { path: "/unlimited", name: "Illimité", thumb: "wordle", blurb: "Jouez autant de parties aléatoires que vous voulez, sans limite quotidienne." },
    { path: "/dordle", name: "Dordle", thumb: "dordle", blurb: "Résolvez deux grilles en parallèle en sept essais." },
    { path: "/quordle", name: "Quordle", thumb: "quordle", blurb: "Résolvez quatre grilles en parallèle en neuf essais." },
    { path: "/octordle", name: "Octordle", thumb: "octordle", blurb: "Résolvez huit grilles en parallèle en treize essais." },
    { path: "/sedecordle", name: "Sedecordle", thumb: "sedecordle", blurb: "Résolvez seize grilles à la fois en vingt-et-un essais." },
    { path: "/spellbee", name: "SpellBee", thumb: "spellbee", blurb: "Formez le plus de mots possible avec sept lettres." },
    { path: "/connect", name: "Connecter", thumb: "connect", blurb: "Regroupez seize mots en quatre groupes cachés de quatre." },
    { path: "/squares", name: "Carrés", thumb: "squares", blurb: "Reliez des lettres adjacentes dans une grille 4×4 pour former des mots." },
    { path: "/custom", name: "Mot Personnalisé", thumb: "custom", blurb: "Cachez votre propre mot et partagez le lien avec des amis." },
    { path: "/multiplayer", name: "Multijoueur", thumb: "multiplayer", blurb: "Affrontez un ami en temps réel dans un salon privé." },
    { path: "/solver", name: "Solveur", thumb: "solver", blurb: "Bloqué ? Saisissez vos indices et voyez toutes les réponses possibles." },
    { path: "/archive", name: "Archives", thumb: "archive", blurb: "Rejouez les énigmes quotidiennes précédentes que vous avez manquées." },
  ],
  languageTitle: "Choisir une langue",
  languageIntro:
    "Wordle est disponible dans de nombreuses langues. Chaque version utilise son propre dictionnaire et sa disposition de clavier, vous pouvez donc jouer dans celle que vous connaissez le mieux.",
  tipsTitle: "Conseils pour jouer à Wordle",
  tips: [
    { title: "Commencez par un mot solide", body: "Choisissez un mot qui couvre plusieurs lettres courantes : un mélange équilibré de voyelles et de consonnes fréquentes donne le plus d'information en un seul essai." },
    { title: "Faites attention à la position", body: "Une case jaune vous dit que la lettre est dans le mot, mais pas là où vous l'avez placée. Essayez une autre position au prochain coup et gardez la liste en tête." },
    { title: "Ne réutilisez pas les lettres grises", body: "Quand une lettre est grise, vous l'avez écartée totalement. Brûler un essai sur un mot qui la contient n'est qu'une perte de tour." },
    { title: "Repérez les motifs", body: "Une langue regorge de formes récurrentes, comme des terminaisons fréquentes et des préfixes habituels, et les remarquer verrouille souvent les dernières cases." },
    { title: "Privilégiez les mots familiers", body: "Quand plusieurs lettres conviennent, penchez pour des mots de tous les jours. La réponse n'est presque jamais obscure." },
    { title: "Écartez tôt des groupes de lettres", body: "Utilisez votre deuxième ou troisième essai pour tester de nouvelles lettres même si cela ne peut pas gagner. Éliminer cinq lettres supplémentaires en vaut souvent la peine." },
    { title: "Restez calme et réfléchissez", body: "Pas de chronomètre. Ralentissez sur les deux derniers essais et passez en revue les candidats restants avant de valider." },
    { title: "Utilisez le solveur avec parcimonie", body: "Le solveur est utile pour apprendre, mais l'employer chaque jour gâche le plaisir. Gardez-le pour les moments où vous êtes vraiment coincé." },
    { title: "Entraînez-vous régulièrement", body: "Plus vous jouez, plus les motifs deviennent familiers. Une courte session quotidienne suffit à garder vos réflexes." },
  ],
  faqTitle: "Questions fréquentes",
  faq: [
    { q: "Combien d'essais ai-je ?", a: "Vous avez six essais pour trouver le mot caché. Chaque essai doit être un vrai mot de la bonne longueur." },
    { q: "Que signifient les couleurs ?", a: "Le vert marque une lettre bien placée, le jaune une lettre dans le mot mais à une autre position, et le gris une lettre absente du mot." },
    { q: "Y a-t-il un nouveau mot chaque jour ?", a: "Oui. Le puzzle quotidien est le même pour tout le monde et change à minuit. Si vous en voulez plus, le mode Illimité ne s'épuise jamais." },
    { q: "Puis-je jouer plus d'une fois par jour ?", a: "Le mot du jour est unique, mais l'Illimité, les variantes par longueur et les parties personnalisées vous laissent jouer autant que vous voulez." },
    { q: "Les lettres peuvent-elles se répéter dans la réponse ?", a: "Oui. Le mot caché peut contenir la même lettre plusieurs fois, alors n'écartez pas les doublons." },
    { q: "Qu'est-ce que le Mode Difficile ?", a: "En Mode Difficile, tout indice révélé doit être réutilisé dans les essais suivants : les verts restent en place et les jaunes doivent apparaître quelque part." },
    { q: "Comment partager mon résultat ?", a: "Une fois terminé, le bouton de partage copie une grille de carrés colorés sans spoiler indiquant combien d'essais il vous a fallu." },
    { q: "Puis-je jouer dans d'autres langues ?", a: "Oui. Utilisez le sélecteur de langue pour changer l'interface et la liste de mots vers l'une des langues prises en charge." },
  ],
  advantagesTitle: "Avantages du jeu Wordle",
  advantages: [
    { icon: "book", title: "Enrichit votre vocabulaire", body: "Deviner et lire de nouveaux mots chaque jour est une façon indolore d'améliorer l'orthographe et le vocabulaire." },
    { icon: "lightning", title: "Gratuit et immédiat", body: "Pas de téléchargement, pas d'inscription, pas de paiement. Ouvrez la page et jouez." },
    { icon: "puzzle", title: "Affûte la logique", body: "Chaque indice réduit l'espace des possibles. Résoudre est un petit exercice quotidien de déduction." },
    { icon: "brain", title: "Un entraînement mental doux", body: "Quelques minutes concentrées de recherche de motifs gardent l'esprit actif sans effort." },
    { icon: "clock", title: "Sans contrainte de temps", body: "Pas de chronomètre. Prenez tout le temps qu'il vous faut pour chaque essai." },
    { icon: "share", title: "Amusant à partager", body: "Comparez votre grille avec amis et famille et voyez qui a résolu en le moins d'essais." },
  ],
  ratingTitle: "Notez le jeu",
  ratingValue: 4.3,
  ratingCount: 3847,
};
