import type { HomeContent } from "./types";

export const id: HomeContent = {
  h1: "Wordle: Permainan Tebak Kata Terbaik",
  intro:
    "Wordle adalah teka-teki harian dengan enam kesempatan untuk menebak kata tersembunyi berisi lima huruf. Setelah setiap tebakan, kotak berubah warna untuk menunjukkan seberapa dekat Anda: hijau untuk huruf di posisi yang tepat, kuning untuk huruf yang ada di kata tetapi di posisi lain, dan abu-abu untuk huruf yang sama sekali tidak ada di kata. Teka-teki baru muncul setiap hari, dan semua orang bermain dengan kata yang sama.",
  howToTitle: "Cara bermain Wordle",
  howToSteps: [
    { title: "Ketik tebakan pertama Anda", body: "Masukkan kata valid lima huruf apa pun dan tekan Enter. Tidak ada hukuman untuk menebak, jadi gunakan percobaan pertama untuk menguji huruf-huruf umum." },
    { title: "Baca warnanya", body: "Hijau berarti hurufnya benar dan di posisi yang tepat. Kuning berarti hurufnya ada di kata tetapi di tempat lain. Abu-abu berarti hurufnya tidak ada di kata." },
    { title: "Perbaiki tebakan berikutnya", body: "Pertahankan huruf hijau di tempatnya, pindahkan huruf kuning ke posisi baru, dan hindari sepenuhnya huruf abu-abu pada percobaan berikutnya." },
    { title: "Pecahkan dalam enam percobaan", body: "Anda memiliki enam tebakan untuk menemukan kata tersembunyi. Setiap tebakan mempersempit kemungkinan, jadi pikirkan baik-baik sebelum mengonfirmasi." },
    { title: "Kembali besok", body: "Kata harian disetel ulang pada tengah malam. Bagikan kotak warna Anda kepada teman dan bandingkan berapa banyak percobaan yang dibutuhkan tanpa membocorkan jawaban." },
  ],
  moreGamesTitle: "Permainan kata lainnya",
  moreGames: [
    { path: "/unlimited", name: "Tanpa Batas", thumb: "wordle", blurb: "Mainkan sebanyak yang Anda mau, tanpa batas harian." },
    { path: "/dordle", name: "Dordle", thumb: "dordle", blurb: "Selesaikan dua papan paralel dalam tujuh tebakan." },
    { path: "/quordle", name: "Quordle", thumb: "quordle", blurb: "Selesaikan empat papan paralel dalam sembilan tebakan." },
    { path: "/octordle", name: "Octordle", thumb: "octordle", blurb: "Selesaikan delapan papan paralel dalam tiga belas tebakan." },
    { path: "/sedecordle", name: "Sedecordle", thumb: "sedecordle", blurb: "Selesaikan enam belas papan sekaligus dalam dua puluh satu tebakan." },
    { path: "/spellbee", name: "SpellBee", thumb: "spellbee", blurb: "Buat sebanyak mungkin kata dari tujuh huruf." },
    { path: "/connect", name: "Hubungkan", thumb: "connect", blurb: "Susun enam belas kata menjadi empat kelompok tersembunyi berisi empat." },
    { path: "/squares", name: "Kotak", thumb: "squares", blurb: "Hubungkan huruf-huruf bertetangga di kisi 4×4 untuk membentuk kata." },
    { path: "/custom", name: "Kata Kustom", thumb: "custom", blurb: "Sembunyikan kata Anda sendiri dan bagikan tautannya kepada teman." },
    { path: "/multiplayer", name: "Multipemain", thumb: "multiplayer", blurb: "Bertanding melawan teman secara real time di ruang pribadi." },
    { path: "/solver", name: "Pemecah", thumb: "solver", blurb: "Mentok? Masukkan petunjuk Anda dan lihat semua jawaban yang mungkin." },
    { path: "/archive", name: "Arsip", thumb: "archive", blurb: "Mainkan ulang teka-teki harian sebelumnya yang Anda lewatkan." },
  ],
  languageTitle: "Pilih bahasa",
  languageIntro:
    "Wordle tersedia dalam banyak bahasa. Setiap versi menggunakan kamus dan tata letak keyboard sendiri, sehingga Anda dapat bermain dalam bahasa yang paling Anda kuasai.",
  tipsTitle: "Tips bermain Wordle",
  tips: [
    { title: "Mulai dengan kata yang kuat", body: "Pilih kata yang mencakup beberapa huruf umum. Perpaduan seimbang antara vokal dan konsonan sering memberi informasi paling banyak dari satu tebakan." },
    { title: "Perhatikan posisi", body: "Kotak kuning memberi tahu bahwa hurufnya ada di kata, hanya tidak di tempat Anda meletakkannya. Coba posisi lain di tebakan berikutnya dan catat di kepala." },
    { title: "Jangan gunakan kembali huruf abu-abu", body: "Begitu huruf menjadi abu-abu, Anda sudah benar-benar menyingkirkannya. Membuang tebakan pada kata yang mengandungnya hanya menghabiskan giliran." },
    { title: "Cari pola huruf", body: "Setiap bahasa memiliki bentuk berulang, seperti akhiran umum dan awalan yang familier, dan menyadarinya sering mengunci kotak-kotak terakhir." },
    { title: "Coba kata yang familiar", body: "Saat beberapa huruf cocok, condongkan ke kata sehari-hari. Jawabannya hampir tidak pernah aneh." },
    { title: "Eliminasi kelompok huruf lebih awal", body: "Gunakan tebakan kedua atau ketiga untuk menguji huruf baru meskipun tidak bisa menang. Menyingkirkan lima huruf lain biasanya sepadan." },
    { title: "Tetap tenang dan pikirkan", body: "Tidak ada jam. Melambatlah di dua tebakan terakhir dan tinjau kandidat yang tersisa di kepala sebelum mengonfirmasi." },
    { title: "Gunakan pemecah dengan bijak", body: "Pemecah hebat untuk belajar, tapi menggunakannya setiap hari menghilangkan kepuasan. Simpan sebagai cadangan saat Anda benar-benar mentok." },
    { title: "Berlatih teratur", body: "Semakin banyak teka-teki yang Anda mainkan, semakin akrab pola-polanya. Putaran harian singkat sudah cukup untuk menjaga keterampilan tetap tajam." },
  ],
  faqTitle: "Pertanyaan yang sering diajukan",
  faq: [
    { q: "Berapa banyak tebakan yang saya dapatkan?", a: "Anda memiliki enam tebakan untuk menemukan kata tersembunyi. Setiap tebakan harus merupakan kata nyata dengan panjang yang benar." },
    { q: "Apa arti warnanya?", a: "Hijau menandai huruf di posisi yang tepat, kuning menandai huruf yang ada di kata tetapi di posisi berbeda, dan abu-abu menandai huruf yang tidak ada di kata." },
    { q: "Apakah ada kata baru setiap hari?", a: "Ya. Teka-teki harian memberi semua orang kata yang sama dan berubah pada tengah malam. Jika ingin lebih banyak, mode Tanpa Batas tidak pernah habis." },
    { q: "Bisakah saya bermain lebih dari sekali sehari?", a: "Kata harian adalah satu per hari, tetapi Tanpa Batas, varian berdasarkan panjang kata, dan permainan kustom memungkinkan Anda bermain sebanyak yang Anda inginkan." },
    { q: "Bisakah huruf berulang dalam jawaban?", a: "Ya. Kata tersembunyi dapat berisi huruf yang sama lebih dari sekali, jadi jangan mengabaikan huruf ganda." },
    { q: "Apa itu Mode Sulit?", a: "Dalam Mode Sulit, setiap petunjuk yang sudah terungkap harus digunakan di setiap tebakan berikutnya: hijau tetap di tempatnya dan kuning harus muncul di suatu tempat." },
    { q: "Bagaimana cara berbagi hasil?", a: "Setelah selesai, tombol bagikan menyalin kotak-kotak warna tanpa spoiler yang menunjukkan berapa banyak percobaan yang dibutuhkan." },
    { q: "Bisakah saya bermain dalam bahasa lain?", a: "Ya. Gunakan pemilih bahasa untuk mengganti antarmuka dan daftar kata ke salah satu bahasa yang didukung." },
  ],
  advantagesTitle: "Keuntungan permainan Wordle",
  advantages: [
    { icon: "book", title: "Memperluas kosakata", body: "Menebak dan membaca kata-kata baru setiap hari adalah cara tanpa rasa sakit untuk memperbaiki ejaan dan pengetahuan kata." },
    { icon: "lightning", title: "Gratis dan langsung", body: "Tanpa unduhan, tanpa pendaftaran, tanpa pembayaran. Buka halaman dan mulai bermain." },
    { icon: "puzzle", title: "Mengasah logika", body: "Setiap petunjuk mempersempit area. Memecahkannya adalah latihan deduksi kecil setiap hari." },
    { icon: "brain", title: "Latihan otak yang ringan", body: "Beberapa menit fokus mencari pola menjaga pikiran tetap aktif tanpa terasa seperti pekerjaan." },
    { icon: "clock", title: "Tanpa tekanan waktu", body: "Tidak ada penghitung waktu. Habiskan waktu sebanyak yang Anda butuhkan untuk setiap tebakan." },
    { icon: "share", title: "Menyenangkan untuk dibagikan", body: "Bandingkan kotak warna Anda dengan keluarga dan teman dan lihat siapa yang menyelesaikan dengan percobaan paling sedikit." },
  ],
  ratingTitle: "Beri peringkat permainan",
  ratingValue: 4.3,
  ratingCount: 3847,
};
