import type { HomeContent } from "./types";

export const it: HomeContent = {
  h1: "Wordle – Il gioco definitivo di indovinare parole",
  intro:
    "Wordle è un puzzle quotidiano in cui hai sei tentativi per indovinare una parola nascosta di cinque lettere. Dopo ogni tentativo, le caselle cambiano colore per mostrarti quanto sei vicino: verde per una lettera al posto giusto, giallo per una lettera che è nella parola ma in un'altra posizione, e grigio per una lettera che non c'è affatto. Ogni giorno esce un nuovo puzzle e tutti giochiamo la stessa parola.",
  howToTitle: "Come giocare a Wordle",
  howToSteps: [
    { title: "Inserisci il primo tentativo", body: "Scrivi una parola valida di cinque lettere e premi Invio. Non c'è penalità per i tentativi, quindi usa il primo per testare lettere comuni." },
    { title: "Leggi i colori", body: "Verde significa che la lettera è corretta e nella posizione giusta. Giallo significa che è nella parola ma altrove. Grigio significa che non è nella parola." },
    { title: "Affina il prossimo tentativo", body: "Tieni le lettere verdi al loro posto, sposta le gialle altrove ed evita del tutto le grigie nel tentativo successivo." },
    { title: "Risolvi in sei tentativi", body: "Hai sei tentativi per trovare la parola nascosta. Ogni tentativo restringe le possibilità, quindi rifletti prima di confermare." },
    { title: "Torna domani", body: "La parola del giorno si resetta a mezzanotte. Condividi la tua griglia colorata con gli amici e confrontate quanti tentativi avete usato senza svelare la risposta." },
  ],
  moreGamesTitle: "Altri giochi di parole",
  moreGames: [
    { path: "/unlimited", name: "Illimitato", thumb: "wordle", blurb: "Gioca quanti puzzle casuali vuoi, senza limite giornaliero." },
    { path: "/dordle", name: "Dordle", thumb: "dordle", blurb: "Risolvi due griglie in parallelo in sette tentativi." },
    { path: "/quordle", name: "Quordle", thumb: "quordle", blurb: "Risolvi quattro griglie in parallelo in nove tentativi." },
    { path: "/octordle", name: "Octordle", thumb: "octordle", blurb: "Risolvi otto griglie in parallelo in tredici tentativi." },
    { path: "/sedecordle", name: "Sedecordle", thumb: "sedecordle", blurb: "Risolvi sedici griglie insieme in ventuno tentativi." },
    { path: "/spellbee", name: "SpellBee", thumb: "spellbee", blurb: "Forma il maggior numero di parole possibile con sette lettere." },
    { path: "/connect", name: "Collega", thumb: "connect", blurb: "Raggruppa sedici parole in quattro gruppi nascosti da quattro." },
    { path: "/squares", name: "Quadrati", thumb: "squares", blurb: "Collega lettere adiacenti in una griglia 4×4 per formare parole." },
    { path: "/custom", name: "Parola Personalizzata", thumb: "custom", blurb: "Nascondi una tua parola e condividi il link con gli amici." },
    { path: "/multiplayer", name: "Multigiocatore", thumb: "multiplayer", blurb: "Sfida un amico in tempo reale in una stanza privata." },
    { path: "/solver", name: "Risolutore", thumb: "solver", blurb: "Bloccato? Inserisci i tuoi indizi e vedi tutte le risposte possibili." },
    { path: "/archive", name: "Archivio", thumb: "archive", blurb: "Rigioca i puzzle quotidiani precedenti che ti sei perso." },
  ],
  languageTitle: "Scegli una lingua",
  languageIntro:
    "Wordle è disponibile in molte lingue. Ogni versione ha il proprio dizionario e layout di tastiera, così puoi giocare in quella che conosci meglio.",
  tipsTitle: "Consigli per giocare a Wordle",
  tips: [
    { title: "Inizia con una parola forte", body: "Scegli una parola che copra più lettere comuni: un mix bilanciato di vocali e consonanti frequenti dà il massimo dell'informazione in un solo tentativo." },
    { title: "Fai attenzione alla posizione", body: "Una casella gialla dice che la lettera c'è, solo non dove l'hai messa. Prova un'altra posizione al prossimo turno e tieni il conto a mente." },
    { title: "Non riutilizzare le lettere grigie", body: "Quando una lettera è grigia l'hai esclusa del tutto. Bruciare un tentativo con una parola che la contiene è solo perdere un turno." },
    { title: "Cerca pattern di lettere", body: "Ogni lingua ha forme ricorrenti — desinenze comuni, prefissi abituali — e notarle spesso blocca le ultime caselle." },
    { title: "Prediligi parole familiari", body: "Quando più lettere combaciano, scegli parole d'uso comune. La risposta non è quasi mai oscura." },
    { title: "Escludi gruppi di lettere presto", body: "Usa il secondo o terzo tentativo per testare lettere nuove anche se non vinci la partita. Eliminare cinque lettere in più di solito conviene." },
    { title: "Stai calmo e ragiona", body: "Non c'è cronometro. Rallenta sugli ultimi due tentativi e ripassa mentalmente i candidati rimasti prima di confermare." },
    { title: "Usa il risolutore con moderazione", body: "È ottimo per imparare, ma usarlo ogni giorno toglie il piacere. Tienilo da parte per quando sei davvero bloccato." },
    { title: "Allenati con regolarità", body: "Più puzzle giochi, più i pattern diventano familiari. Una breve sessione quotidiana basta per restare in forma." },
  ],
  faqTitle: "Domande frequenti",
  faq: [
    { q: "Quanti tentativi ho?", a: "Hai sei tentativi per trovare la parola nascosta. Ogni tentativo deve essere una parola reale della lunghezza corretta." },
    { q: "Cosa significano i colori?", a: "Il verde indica una lettera nella posizione giusta, il giallo una lettera presente nella parola ma in un'altra posizione, e il grigio una lettera assente." },
    { q: "C'è una parola nuova ogni giorno?", a: "Sì. Il puzzle quotidiano è lo stesso per tutti e cambia a mezzanotte. Se ne vuoi di più, la modalità Illimitato non si esaurisce mai." },
    { q: "Posso giocare più di una volta al giorno?", a: "La parola giornaliera è una sola, ma Illimitato, le varianti per lunghezza e i giochi personalizzati ti lasciano giocare quanto vuoi." },
    { q: "Le lettere possono ripetersi nella risposta?", a: "Sì. La parola nascosta può contenere la stessa lettera più volte, quindi non escludere le lettere doppie." },
    { q: "Cos'è la Modalità Difficile?", a: "In Modalità Difficile ogni indizio rivelato deve essere usato nei tentativi successivi: i verdi restano al loro posto e i gialli devono comparire da qualche parte." },
    { q: "Come condivido il risultato?", a: "Quando finisci, il pulsante di condivisione copia una griglia di quadrati colorati senza spoiler che mostra quanti tentativi hai usato." },
    { q: "Posso giocare in altre lingue?", a: "Sì. Usa il selettore di lingue per cambiare interfaccia e lista di parole in una delle lingue supportate." },
  ],
  advantagesTitle: "Vantaggi del gioco Wordle",
  advantages: [
    { icon: "book", title: "Arricchisce il vocabolario", body: "Indovinare e leggere nuove parole ogni giorno è un modo indolore di migliorare ortografia e lessico." },
    { icon: "lightning", title: "Gratis e immediato", body: "Niente download, niente registrazione, niente pagamenti. Apri la pagina e gioca." },
    { icon: "puzzle", title: "Affina la logica", body: "Ogni indizio riduce lo spazio delle possibilità. Risolvere è un piccolo esercizio quotidiano di deduzione." },
    { icon: "brain", title: "Allenamento mentale leggero", body: "Qualche minuto concentrato di ricerca di pattern mantiene la mente attiva senza sembrare fatica." },
    { icon: "clock", title: "Nessuna fretta", body: "Non c'è cronometro. Prenditi tutto il tempo che vuoi per ogni tentativo." },
    { icon: "share", title: "Divertente da condividere", body: "Confronta la tua griglia con amici e famiglia e guardate chi l'ha risolto in meno tentativi." },
  ],
  ratingTitle: "Vota il gioco",
  ratingValue: 4.3,
  ratingCount: 3847,
};
