import type { HomeContent } from "./types";

export const nl: HomeContent = {
  h1: "Wordle: Het ultieme woordraadspel",
  intro:
    "Wordle is een dagelijkse puzzel waarin je zes pogingen hebt om een verborgen woord van vijf letters te raden. Na elke poging veranderen de vakjes van kleur om aan te geven hoe dichtbij je bent: groen voor een letter op de juiste plek, geel voor een letter die in het woord zit maar op een andere plek, en grijs voor een letter die helemaal niet in het woord voorkomt. Elke dag verschijnt er een nieuwe puzzel en iedereen speelt hetzelfde woord.",
  howToTitle: "Hoe speel je Wordle",
  howToSteps: [
    { title: "Voer je eerste gok in", body: "Typ een geldig woord van vijf letters en druk op Enter. Gokken kost niets, dus gebruik je eerste poging om veelgebruikte letters te testen." },
    { title: "Lees de kleuren", body: "Groen betekent dat de letter klopt en op de juiste plek staat. Geel betekent dat de letter in het woord zit, maar ergens anders. Grijs betekent dat de letter niet in het woord voorkomt." },
    { title: "Verfijn de volgende gok", body: "Houd de groene letters op hun plek, verplaats de gele en vermijd de grijze volledig bij de volgende poging." },
    { title: "Los het op in zes pogingen", body: "Je hebt zes pogingen om het verborgen woord te vinden. Elke gok versmalt de mogelijkheden, dus denk goed na voor je bevestigt." },
    { title: "Kom morgen terug", body: "Het dagwoord wisselt om middernacht. Deel je gekleurde raster met vrienden en vergelijk hoeveel pogingen jullie nodig hadden zonder het antwoord te verklappen." },
  ],
  moreGamesTitle: "Meer woordspellen",
  moreGames: [
    { path: "/unlimited", name: "Onbeperkt", thumb: "wordle", blurb: "Speel zoveel willekeurige puzzels als je wilt, geen dagelijkse limiet." },
    { path: "/dordle", name: "Dordle", thumb: "dordle", blurb: "Los twee borden parallel op in zeven pogingen." },
    { path: "/quordle", name: "Quordle", thumb: "quordle", blurb: "Los vier borden parallel op in negen pogingen." },
    { path: "/octordle", name: "Octordle", thumb: "octordle", blurb: "Los acht borden parallel op in dertien pogingen." },
    { path: "/sedecordle", name: "Sedecordle", thumb: "sedecordle", blurb: "Los zestien borden tegelijk op in eenentwintig pogingen." },
    { path: "/spellbee", name: "SpellBee", thumb: "spellbee", blurb: "Maak zoveel mogelijk woorden van zeven letters." },
    { path: "/connect", name: "Verbinden", thumb: "connect", blurb: "Sorteer zestien woorden in vier verborgen groepen van vier." },
    { path: "/squares", name: "Vierkanten", thumb: "squares", blurb: "Verbind naburige letters in een 4×4 raster tot woorden." },
    { path: "/custom", name: "Eigen Woord", thumb: "custom", blurb: "Verberg je eigen woord en deel de link met vrienden." },
    { path: "/multiplayer", name: "Multiplayer", thumb: "multiplayer", blurb: "Wedijver in realtime met een vriend in een privékamer." },
    { path: "/solver", name: "Oplosser", thumb: "solver", blurb: "Vast? Voer je aanwijzingen in en zie alle mogelijke antwoorden." },
    { path: "/archive", name: "Archief", thumb: "archive", blurb: "Speel oudere dagpuzzels die je gemist hebt." },
  ],
  languageTitle: "Kies een taal",
  languageIntro:
    "Wordle is in veel talen beschikbaar. Elke versie gebruikt zijn eigen woordenboek en toetsenbordindeling, zodat je kunt spelen in de taal die je het beste kent.",
  tipsTitle: "Tips om Wordle te spelen",
  tips: [
    { title: "Start met een sterk woord", body: "Kies een woord dat meerdere veelvoorkomende letters bevat: een evenwichtige mix van klinkers en frequente medeklinkers geeft de meeste informatie in één poging." },
    { title: "Let op de positie", body: "Een geel vakje vertelt je dat de letter in het woord zit, alleen niet waar je hem hebt geplaatst. Probeer volgende keer een andere positie en houd het in je hoofd bij." },
    { title: "Gebruik grijze letters niet opnieuw", body: "Zodra een letter grijs is, heb je hem volledig uitgesloten. Een gok verspillen aan een woord dat hem bevat is gewoon een verloren beurt." },
    { title: "Zoek naar letterpatronen", body: "Elke taal kent terugkerende vormen, zoals vaste uitgangen en gangbare voorvoegsels. Die opmerken zet vaak de laatste vakjes vast." },
    { title: "Probeer vertrouwde woorden", body: "Als meerdere letters passen, ga voor alledaagse woorden. Het antwoord is bijna nooit obscuur." },
    { title: "Sluit groepen vroeg uit", body: "Gebruik je tweede of derde gok om nieuwe letters te testen, ook als je daarmee niet kunt winnen. Vijf letters extra uitsluiten loont meestal." },
    { title: "Blijf rustig en denk na", body: "Er is geen klok. Vertraag bij de laatste twee pogingen en loop de overgebleven kandidaten in gedachten af voor je bevestigt." },
    { title: "Gebruik de solver met mate", body: "De solver is fijn om mee te leren, maar dagelijks gebruik haalt de lol eraf. Bewaar hem voor als je echt vastzit." },
    { title: "Oefen regelmatig", body: "Hoe meer puzzels je speelt, hoe vertrouwder de patronen worden. Een korte ronde per dag is genoeg om scherp te blijven." },
  ],
  faqTitle: "Veelgestelde vragen",
  faq: [
    { q: "Hoeveel pogingen krijg ik?", a: "Je hebt zes pogingen om het verborgen woord te vinden. Elke poging moet een echt woord van de juiste lengte zijn." },
    { q: "Wat betekenen de kleuren?", a: "Groen markeert een letter op de juiste plek, geel een letter die in het woord zit maar op een andere plek, en grijs een letter die niet in het woord voorkomt." },
    { q: "Is er elke dag een nieuw woord?", a: "Ja. De dagelijkse puzzel is voor iedereen hetzelfde en wisselt om middernacht. Wil je meer, dan raakt de Onbeperkt-modus nooit op." },
    { q: "Mag ik vaker dan één keer per dag spelen?", a: "Het dagwoord is één keer per dag, maar Onbeperkt, de varianten op woordlengte en eigen spellen laten je spelen zoveel je wilt." },
    { q: "Kunnen letters herhalen in het antwoord?", a: "Ja. Het verborgen woord kan dezelfde letter meerdere keren bevatten, dus sluit dubbele letters niet uit." },
    { q: "Wat is de moeilijke modus?", a: "In de moeilijke modus moet elke onthulde aanwijzing in elke volgende poging worden gebruikt: groene letters blijven staan en gele moeten ergens verschijnen." },
    { q: "Hoe deel ik mijn resultaat?", a: "Als je klaar bent, kopieert de deelknop een spoilervrij raster van gekleurde vakjes dat laat zien hoeveel pogingen je nodig had." },
    { q: "Kan ik in andere talen spelen?", a: "Ja. Gebruik de taalkeuze om de interface en de woordenlijst te wisselen naar een van de ondersteunde talen." },
  ],
  advantagesTitle: "Voordelen van het Wordle-spel",
  advantages: [
    { icon: "book", title: "Vergroot je woordenschat", body: "Elke dag nieuwe woorden raden en lezen is een pijnloze manier om spelling en taalkennis op te pikken." },
    { icon: "lightning", title: "Gratis en direct", body: "Geen download, geen registratie, geen betaling. Open de pagina en begin met spelen." },
    { icon: "puzzle", title: "Scherpt je logica", body: "Elke aanwijzing verkleint het speelveld. Het oplossen is een kleine dagelijkse oefening in deductie." },
    { icon: "brain", title: "Een milde hersentraining", body: "Een paar geconcentreerde minuten patronen zoeken houdt je hoofd actief zonder werk te voelen." },
    { icon: "clock", title: "Geen tijdsdruk", body: "Er is geen timer. Neem zoveel tijd als je nodig hebt voor elke gok." },
    { icon: "share", title: "Leuk om te delen", body: "Vergelijk je gekleurde raster met vrienden en familie en kijk wie het in de minste pogingen oploste." },
  ],
  ratingTitle: "Beoordeel het spel",
  ratingValue: 4.3,
  ratingCount: 3847,
};
