import type { HomeContent } from "./types";

export const pl: HomeContent = {
  h1: "Wordle – Najlepsza gra w zgadywanie słów",
  intro:
    "Wordle to codzienna łamigłówka, w której masz sześć prób, by odgadnąć ukryte pięcioliterowe słowo. Po każdej próbie kafelki zmieniają kolor, pokazując, jak blisko jesteś: zielony oznacza literę we właściwym miejscu, żółty — literę, która jest w słowie, ale w innym miejscu, a szary — literę, której w słowie nie ma w ogóle. Każdego dnia pojawia się nowa zagadka, a wszyscy grają to samo słowo.",
  howToTitle: "Jak grać w Wordle",
  howToSteps: [
    { title: "Wpisz pierwszą próbę", body: "Wpisz dowolne poprawne pięcioliterowe słowo i naciśnij Enter. Za zgadywanie nie ma kary, więc wykorzystaj pierwszą próbę do sprawdzenia popularnych liter." },
    { title: "Czytaj kolory", body: "Zielony oznacza, że litera jest poprawna i we właściwym miejscu. Żółty oznacza, że jest w słowie, ale gdzie indziej. Szary oznacza, że nie ma jej w słowie." },
    { title: "Doprecyzuj kolejną próbę", body: "Zachowaj zielone litery na ich miejscach, przesuń żółte w nowe miejsce, a szare całkowicie pomiń w następnej próbie." },
    { title: "Rozwiąż w sześciu próbach", body: "Masz sześć prób, by znaleźć ukryte słowo. Każda próba zawęża możliwości, więc pomyśl, zanim potwierdzisz." },
    { title: "Wróć jutro", body: "Codzienne słowo resetuje się o północy. Podziel się swoją kolorową siatką ze znajomymi i porównajcie, ile prób wam zajęło, bez zdradzania odpowiedzi." },
  ],
  moreGamesTitle: "Więcej gier słownych",
  moreGames: [
    { path: "/unlimited", name: "Bez Limitu", thumb: "wordle", blurb: "Graj tyle losowych zagadek, ile chcesz, bez dziennego limitu." },
    { path: "/dordle", name: "Dordle", thumb: "dordle", blurb: "Rozwiąż dwie plansze równolegle w siedmiu próbach." },
    { path: "/quordle", name: "Quordle", thumb: "quordle", blurb: "Rozwiąż cztery plansze równolegle w dziewięciu próbach." },
    { path: "/octordle", name: "Octordle", thumb: "octordle", blurb: "Rozwiąż osiem plansz równolegle w trzynastu próbach." },
    { path: "/sedecordle", name: "Sedecordle", thumb: "sedecordle", blurb: "Rozwiąż szesnaście plansz naraz w dwudziestu jeden próbach." },
    { path: "/spellbee", name: "SpellBee", thumb: "spellbee", blurb: "Ułóż jak najwięcej słów z siedmiu liter." },
    { path: "/connect", name: "Połącz", thumb: "connect", blurb: "Posortuj szesnaście słów na cztery ukryte grupy po cztery." },
    { path: "/squares", name: "Kwadraty", thumb: "squares", blurb: "Łącz sąsiednie litery w siatce 4×4, by ułożyć słowa." },
    { path: "/custom", name: "Własne Słowo", thumb: "custom", blurb: "Ukryj własne słowo i podziel się linkiem ze znajomymi." },
    { path: "/multiplayer", name: "Wieloosobowa", thumb: "multiplayer", blurb: "Rywalizuj z przyjacielem w czasie rzeczywistym w prywatnym pokoju." },
    { path: "/solver", name: "Solver", thumb: "solver", blurb: "Utknąłeś? Wpisz wskazówki i zobacz wszystkie możliwe odpowiedzi." },
    { path: "/archive", name: "Archiwum", thumb: "archive", blurb: "Powtórz wcześniejsze codzienne zagadki, które pominąłeś." },
  ],
  languageTitle: "Wybierz język",
  languageIntro:
    "Wordle jest dostępny w wielu językach. Każda wersja używa własnego słownika i układu klawiatury, więc możesz grać w tej, którą znasz najlepiej.",
  tipsTitle: "Wskazówki do gry w Wordle",
  tips: [
    { title: "Zacznij od mocnego słowa", body: "Wybierz słowo zawierające kilka popularnych liter — zrównoważona mieszanka samogłosek i częstych spółgłosek daje najwięcej informacji z jednej próby." },
    { title: "Zwracaj uwagę na pozycję", body: "Żółty kafelek mówi, że litera jest w słowie, tylko nie tam, gdzie ją umieściłeś. Spróbuj innego miejsca przy kolejnej próbie i zapamiętuj." },
    { title: "Nie używaj ponownie szarych liter", body: "Gdy litera jest szara, całkowicie ją wykluczasz. Marnowanie próby na słowo, które ją zawiera, to po prostu stracony ruch." },
    { title: "Szukaj wzorców liter", body: "Każdy język ma powtarzające się formy — typowe końcówki, znane przedrostki — a ich zauważanie często blokuje ostatnie kafelki." },
    { title: "Próbuj znanych słów", body: "Gdy pasuje kilka liter, wybieraj słowa z życia codziennego. Odpowiedź prawie nigdy nie jest niejasna." },
    { title: "Eliminuj grupy liter wcześnie", body: "Wykorzystaj drugą lub trzecią próbę na sprawdzenie nowych liter, nawet jeśli nie możesz wygrać. Wyeliminowanie pięciu kolejnych liter zwykle się opłaca." },
    { title: "Zachowaj spokój i myśl", body: "Nie ma zegara. Zwolnij przy dwóch ostatnich próbach i w głowie przejdź pozostałych kandydatów, zanim potwierdzisz." },
    { title: "Korzystaj z solvera z umiarem", body: "Solver świetnie nadaje się do nauki, ale codzienne używanie odbiera satysfakcję. Zostaw go na chwile, gdy naprawdę utkniesz." },
    { title: "Ćwicz regularnie", body: "Im więcej zagadek rozwiążesz, tym wzorce stają się bardziej znajome. Krótka codzienna runda wystarczy, by utrzymać formę." },
  ],
  faqTitle: "Najczęściej zadawane pytania",
  faq: [
    { q: "Ile mam prób?", a: "Masz sześć prób, by znaleźć ukryte słowo. Każda próba musi być prawdziwym słowem o właściwej długości." },
    { q: "Co oznaczają kolory?", a: "Zielony oznacza literę na właściwej pozycji, żółty literę, która jest w słowie, ale na innej pozycji, a szary literę, której w słowie nie ma." },
    { q: "Czy każdego dnia jest nowe słowo?", a: "Tak. Codzienna zagadka jest taka sama dla wszystkich i zmienia się o północy. Jeśli chcesz więcej, tryb Bez Limitu nigdy się nie kończy." },
    { q: "Czy mogę grać częściej niż raz dziennie?", a: "Codzienne słowo jest jedno na dzień, ale Bez Limitu, warianty z różną długością słów i własne gry pozwalają grać tyle, ile chcesz." },
    { q: "Czy litery mogą się powtarzać w odpowiedzi?", a: "Tak. Ukryte słowo może zawierać tę samą literę więcej niż raz, więc nie wykluczaj podwojonych liter." },
    { q: "Czym jest tryb trudny?", a: "W trybie trudnym każda odsłonięta wskazówka musi być użyta w kolejnych próbach: zielone zostają na miejscu, a żółte muszą gdzieś się pojawić." },
    { q: "Jak udostępnić wynik?", a: "Po zakończeniu przycisk udostępniania kopiuje wolną od spoilerów siatkę kolorowych kwadratów pokazującą, ile prób ci zajęło." },
    { q: "Czy mogę grać w innych językach?", a: "Tak. Użyj przełącznika języka, by przełączyć interfejs i listę słów na jeden z obsługiwanych języków." },
  ],
  advantagesTitle: "Zalety gry Wordle",
  advantages: [
    { icon: "book", title: "Poszerza słownictwo", body: "Codzienne odgadywanie i czytanie nowych słów to bezbolesny sposób na poprawę ortografii i znajomości języka." },
    { icon: "lightning", title: "Za darmo i od razu", body: "Bez pobierania, bez rejestracji, bez płatności. Otwórz stronę i zacznij grać." },
    { icon: "puzzle", title: "Wyostrza logikę", body: "Każda wskazówka zawęża pole. Rozwiązywanie to mały codzienny trening dedukcji." },
    { icon: "brain", title: "Delikatny trening mózgu", body: "Kilka skupionych minut szukania wzorców utrzymuje umysł w gotowości, bez wrażenia pracy." },
    { icon: "clock", title: "Bez presji czasu", body: "Nie ma stopera. Poświęć tyle czasu, ile potrzebujesz na każdy ruch." },
    { icon: "share", title: "Fajnie się dzielić", body: "Porównaj swoją kolorową siatkę z rodziną i przyjaciółmi i zobacz, kto rozwiązał w mniejszej liczbie prób." },
  ],
  ratingTitle: "Oceń grę",
  ratingValue: 4.3,
  ratingCount: 3847,
};
