import type { HomeContent } from "./types";

export const pt: HomeContent = {
  h1: "Wordle – O jogo definitivo de adivinhar palavras",
  intro:
    "Wordle é um quebra-cabeça diário em que você tem seis tentativas para adivinhar uma palavra oculta de cinco letras. Após cada tentativa, as casas mudam de cor para mostrar o quanto você se aproximou: verde para uma letra na posição certa, amarelo para uma letra que está na palavra mas em outro lugar, e cinza para uma letra que não está na palavra. Todos os dias um quebra-cabeça novo é publicado e todo mundo joga a mesma palavra.",
  howToTitle: "Como jogar Wordle",
  howToSteps: [
    { title: "Digite o primeiro palpite", body: "Escreva qualquer palavra válida de cinco letras e pressione Enter. Não há penalidade por chutar, então use a primeira tentativa para testar letras comuns." },
    { title: "Leia as cores", body: "Verde significa que a letra está correta e na posição certa. Amarelo significa que a letra está na palavra mas em outro lugar. Cinza significa que a letra não está na palavra." },
    { title: "Refine o próximo palpite", body: "Mantenha as letras verdes no lugar, mova as amarelas para outra posição e evite totalmente as cinzas na próxima tentativa." },
    { title: "Resolva em seis tentativas", body: "Você tem seis tentativas para encontrar a palavra oculta. Cada palpite reduz as possibilidades, então pense antes de confirmar." },
    { title: "Volte amanhã", body: "A palavra diária reinicia à meia-noite. Compartilhe sua grade de cores com os amigos e comparem quantas tentativas foram necessárias sem entregar a resposta." },
  ],
  moreGamesTitle: "Mais jogos de palavras",
  moreGames: [
    { path: "/unlimited", name: "Ilimitado", thumb: "wordle", blurb: "Jogue quantas partidas aleatórias quiser, sem limite diário." },
    { path: "/dordle", name: "Dordle", thumb: "dordle", blurb: "Resolva dois tabuleiros em paralelo em sete tentativas." },
    { path: "/quordle", name: "Quordle", thumb: "quordle", blurb: "Resolva quatro tabuleiros em paralelo em nove tentativas." },
    { path: "/octordle", name: "Octordle", thumb: "octordle", blurb: "Resolva oito tabuleiros em paralelo em treze tentativas." },
    { path: "/sedecordle", name: "Sedecordle", thumb: "sedecordle", blurb: "Resolva dezesseis tabuleiros ao mesmo tempo em vinte e uma tentativas." },
    { path: "/spellbee", name: "SpellBee", thumb: "spellbee", blurb: "Forme o máximo de palavras possível com sete letras." },
    { path: "/connect", name: "Conectar", thumb: "connect", blurb: "Agrupe dezesseis palavras em quatro grupos ocultos de quatro." },
    { path: "/squares", name: "Quadrados", thumb: "squares", blurb: "Ligue letras adjacentes em uma grade 4×4 para formar palavras." },
    { path: "/custom", name: "Palavra Personalizada", thumb: "custom", blurb: "Esconda sua própria palavra e compartilhe o link com amigos." },
    { path: "/multiplayer", name: "Multijogador", thumb: "multiplayer", blurb: "Dispute em tempo real contra um amigo em uma sala privada." },
    { path: "/solver", name: "Solucionador", thumb: "solver", blurb: "Travou? Insira suas pistas e veja todas as respostas possíveis." },
    { path: "/archive", name: "Arquivo", thumb: "archive", blurb: "Refaça quebra-cabeças diários anteriores que você perdeu." },
  ],
  languageTitle: "Escolha um idioma",
  languageIntro:
    "Wordle está disponível em vários idiomas. Cada versão usa o próprio dicionário e layout de teclado, então você pode jogar no idioma que conhece melhor.",
  tipsTitle: "Dicas para jogar Wordle",
  tips: [
    { title: "Comece com uma palavra forte", body: "Escolha uma palavra que cubra várias letras comuns: uma mistura equilibrada de vogais e consoantes frequentes traz o máximo de informação de um palpite." },
    { title: "Preste atenção à posição", body: "Uma casa amarela diz que a letra está na palavra, só não onde você a colocou. Tente outra posição na próxima e mantenha o controle mental." },
    { title: "Não reutilize letras cinzas", body: "Quando uma letra é cinza, você já a descartou por completo. Queimar um palpite com uma palavra que a contém é só perder o turno." },
    { title: "Procure padrões de letras", body: "Cada idioma tem muitos padrões recorrentes — terminações comuns, prefixos habituais — e percebê-los costuma travar as últimas casas." },
    { title: "Prefira palavras familiares", body: "Quando várias letras encaixam, escolha palavras do dia a dia. A resposta quase nunca é obscura." },
    { title: "Descarte grupos cedo", body: "Use o segundo ou terceiro palpite para testar letras novas, mesmo que não dê para vencer a rodada. Eliminar mais cinco letras geralmente vale a pena." },
    { title: "Mantenha a calma e pense", body: "Não há cronômetro. Vá com calma nos dois últimos palpites e revise mentalmente os candidatos restantes antes de confirmar." },
    { title: "Use o solucionador com moderação", body: "É ótimo para aprender, mas usar todo dia tira a graça. Guarde para quando estiver realmente travado." },
    { title: "Pratique com regularidade", body: "Quanto mais partidas jogar, mais familiares os padrões ficam. Uma rodada curta por dia já mantém você afiado." },
  ],
  faqTitle: "Perguntas frequentes",
  faq: [
    { q: "Quantas tentativas eu tenho?", a: "Você tem seis tentativas para encontrar a palavra oculta. Cada palpite precisa ser uma palavra real com o tamanho certo." },
    { q: "O que significam as cores?", a: "Verde marca uma letra na posição certa, amarelo marca uma letra que está na palavra mas em outra posição, e cinza marca uma letra que não está na palavra." },
    { q: "Existe uma palavra nova todo dia?", a: "Sim. O quebra-cabeça diário é o mesmo para todos e muda à meia-noite. Se quiser mais, o modo Ilimitado nunca acaba." },
    { q: "Posso jogar mais de uma vez por dia?", a: "A palavra diária é uma por dia, mas o Ilimitado, as variantes por tamanho de palavra e os jogos personalizados deixam você jogar à vontade." },
    { q: "Letras podem repetir na resposta?", a: "Sim. A palavra oculta pode ter a mesma letra mais de uma vez, então não descarte letras duplicadas." },
    { q: "O que é o Modo Difícil?", a: "No Modo Difícil, qualquer pista revelada precisa ser usada em todos os palpites seguintes: verdes ficam no lugar e amarelas precisam aparecer em alguma posição." },
    { q: "Como compartilho meu resultado?", a: "Ao terminar, o botão de compartilhar copia uma grade de quadrados coloridos sem spoiler mostrando quantas tentativas você usou." },
    { q: "Posso jogar em outros idiomas?", a: "Sim. Use o seletor de idiomas para trocar a interface e a lista de palavras para um dos idiomas suportados." },
  ],
  advantagesTitle: "Vantagens do jogo Wordle",
  advantages: [
    { icon: "book", title: "Aumenta o vocabulário", body: "Adivinhar e ler palavras novas todos os dias é uma forma indolor de melhorar ortografia e vocabulário." },
    { icon: "lightning", title: "Grátis e instantâneo", body: "Sem download, sem cadastro, sem pagamento. Abra a página e comece a jogar." },
    { icon: "puzzle", title: "Afia a lógica", body: "Cada pista reduz o espaço de possibilidades. Resolver é um pequeno exercício diário de dedução." },
    { icon: "brain", title: "Um treino mental leve", body: "Alguns minutos de busca por padrões mantêm a mente ativa sem parecer trabalho." },
    { icon: "clock", title: "Sem pressa de tempo", body: "Não há cronômetro. Leve o tempo que quiser para pensar cada palpite." },
    { icon: "share", title: "Divertido de compartilhar", body: "Compare sua grade com a família e os amigos e veja quem resolveu em menos tentativas." },
  ],
  ratingTitle: "Avalie o jogo",
  ratingValue: 4.3,
  ratingCount: 3847,
};
