import type { HomeContent } from "./types";

export const sv: HomeContent = {
  h1: "Wordle: Det ultimata ordgissningsspelet",
  intro:
    "Wordle är ett dagligt ordpussel där du har sex försök på dig att gissa ett dolt fembokstavsord. Efter varje gissning byter rutorna färg för att visa hur nära du är: grön för en bokstav på rätt plats, gul för en bokstav som finns i ordet men på fel plats, och grå för en bokstav som inte finns i ordet alls. Varje dag släpps ett nytt pussel och alla spelar samma ord.",
  howToTitle: "Så spelar du Wordle",
  howToSteps: [
    { title: "Skriv din första gissning", body: "Skriv vilket giltigt ord på fem bokstäver som helst och tryck på Retur. Gissningar kostar inget, så använd första försöket för att testa vanliga bokstäver." },
    { title: "Läs färgerna", body: "Grön betyder att bokstaven är rätt och på rätt plats. Gul betyder att den finns i ordet men någon annanstans. Grå betyder att den inte finns i ordet." },
    { title: "Förfina nästa gissning", body: "Behåll de gröna bokstäverna på plats, flytta de gula till en ny ruta och undvik de grå helt vid nästa försök." },
    { title: "Lös det på sex försök", body: "Du har sex gissningar för att hitta det dolda ordet. Varje gissning smalnar av möjligheterna, så tänk efter innan du bekräftar." },
    { title: "Kom tillbaka i morgon", body: "Dagens ord nollställs vid midnatt. Dela ditt färgade rutnät med vänner och jämför hur många försök det tog utan att avslöja svaret." },
  ],
  moreGamesTitle: "Fler ordspel",
  moreGames: [
    { path: "/unlimited", name: "Obegränsat", thumb: "wordle", blurb: "Spela hur många slumpmässiga pussel du vill, utan daglig gräns." },
    { path: "/dordle", name: "Dordle", thumb: "dordle", blurb: "Lös två brädor parallellt på sju försök." },
    { path: "/quordle", name: "Quordle", thumb: "quordle", blurb: "Lös fyra brädor parallellt på nio försök." },
    { path: "/octordle", name: "Octordle", thumb: "octordle", blurb: "Lös åtta brädor parallellt på tretton försök." },
    { path: "/sedecordle", name: "Sedecordle", thumb: "sedecordle", blurb: "Lös sexton brädor samtidigt på tjugoett försök." },
    { path: "/spellbee", name: "SpellBee", thumb: "spellbee", blurb: "Bilda så många ord du kan av sju bokstäver." },
    { path: "/connect", name: "Koppla", thumb: "connect", blurb: "Sortera sexton ord i fyra dolda grupper om fyra." },
    { path: "/squares", name: "Rutor", thumb: "squares", blurb: "Koppla intilliggande bokstäver i ett 4×4-rutnät för att stava ord." },
    { path: "/custom", name: "Eget Ord", thumb: "custom", blurb: "Göm ditt eget ord och dela länken med vänner." },
    { path: "/multiplayer", name: "Flerspelare", thumb: "multiplayer", blurb: "Tävla mot en vän i realtid i ett privat rum." },
    { path: "/solver", name: "Lösare", thumb: "solver", blurb: "Fast? Skriv in dina ledtrådar och se alla möjliga svar." },
    { path: "/archive", name: "Arkiv", thumb: "archive", blurb: "Spela om tidigare dagspussel du kanske missat." },
  ],
  languageTitle: "Välj språk",
  languageIntro:
    "Wordle finns på många språk. Varje version använder sin egen ordlista och tangentbordslayout, så du kan spela på det språk du kan bäst.",
  tipsTitle: "Tips för att spela Wordle",
  tips: [
    { title: "Börja med ett starkt ord", body: "Välj ett ord som täcker flera vanliga bokstäver. En balanserad mix av vokaler och vanliga konsonanter ger mest information från en gissning." },
    { title: "Tänk på positionen", body: "En gul ruta säger att bokstaven finns i ordet, men inte där du satte den. Pröva en annan plats nästa gång och håll koll i huvudet." },
    { title: "Återanvänd inte gråa bokstäver", body: "När en bokstav är grå har du uteslutit den helt. Att slösa en gissning på ett ord med den är bara en bortkastad runda." },
    { title: "Leta efter bokstavsmönster", body: "Varje språk har återkommande former, som vanliga ändelser och kända prefix, och att märka dem låser ofta fast de sista rutorna." },
    { title: "Pröva vanliga ord", body: "När flera bokstäver passar, luta åt vardagliga ord. Svaret är nästan aldrig obskyrt." },
    { title: "Uteslut grupper av bokstäver tidigt", body: "Använd din andra eller tredje gissning för att testa nya bokstäver även om du inte kan vinna rundan. Att eliminera fem bokstäver till brukar löna sig." },
    { title: "Var lugn och tänk efter", body: "Det finns ingen klocka. Sakta ner på de sista två gissningarna och gå igenom kvarvarande kandidater i huvudet innan du bekräftar." },
    { title: "Använd lösaren sparsamt", body: "Lösaren är bra att lära sig av, men dagligt bruk tar bort glädjen. Spara den till när du verkligen kör fast." },
    { title: "Träna regelbundet", body: "Ju fler pussel du spelar, desto mer bekanta blir mönstren. En kort daglig runda räcker för att hålla formen." },
  ],
  faqTitle: "Vanliga frågor",
  faq: [
    { q: "Hur många gissningar har jag?", a: "Du har sex gissningar för att hitta det dolda ordet. Varje gissning måste vara ett riktigt ord med rätt längd." },
    { q: "Vad betyder färgerna?", a: "Grön markerar en bokstav på rätt plats, gul en bokstav som finns i ordet men på annan plats, och grå en bokstav som inte finns i ordet." },
    { q: "Är det ett nytt ord varje dag?", a: "Ja. Dagens pussel är samma för alla och byts vid midnatt. Vill du spela mer tar Obegränsat-läget aldrig slut." },
    { q: "Kan jag spela mer än en gång per dag?", a: "Dagens ord är en gång per dag, men Obegränsat, varianterna med olika ordlängd och egna spel låter dig spela hur mycket du vill." },
    { q: "Kan bokstäver upprepas i svaret?", a: "Ja. Det dolda ordet kan innehålla samma bokstav flera gånger, så uteslut inte dubblade bokstäver." },
    { q: "Vad är svår nivå?", a: "I svår nivå måste varje avslöjad ledtråd användas i alla efterföljande gissningar: gröna stannar kvar och gula måste finnas med någonstans." },
    { q: "Hur delar jag mitt resultat?", a: "När du är klar kopierar dela-knappen ett spoilerfritt rutnät av färgade rutor som visar hur många försök du behövde." },
    { q: "Kan jag spela på andra språk?", a: "Ja. Använd språkväljaren för att byta gränssnitt och ordlista till ett av de språk som stöds." },
  ],
  advantagesTitle: "Fördelar med Wordle-spelet",
  advantages: [
    { icon: "book", title: "Bygger ditt ordförråd", body: "Att gissa och läsa nya ord varje dag är ett smärtfritt sätt att förbättra stavning och språkkunskap." },
    { icon: "lightning", title: "Gratis och direkt", body: "Ingen nedladdning, ingen registrering, ingen betalning. Öppna sidan och börja spela." },
    { icon: "puzzle", title: "Skärper logiken", body: "Varje ledtråd smalnar av fältet. Att lösa är en liten daglig deduktionsövning." },
    { icon: "brain", title: "En mild hjärnträning", body: "Några koncentrerade minuter mönsterletande håller huvudet aktivt utan att kännas som jobb." },
    { icon: "clock", title: "Ingen tidspress", body: "Det finns ingen timer. Ta så lång tid du vill för varje gissning." },
    { icon: "share", title: "Roligt att dela", body: "Jämför ditt färgrutnät med familj och vänner och se vem som löste det på minst antal försök." },
  ],
  ratingTitle: "Betygsätt spelet",
  ratingValue: 4.3,
  ratingCount: 3847,
};
