import type { HomeContent } from "./types";

export const tr: HomeContent = {
  h1: "Wordle – Nihai Kelime Tahmin Oyunu",
  intro:
    "Wordle, gizli beş harfli bir kelimeyi tahmin etmek için altı hakkınızın olduğu günlük bir kelime bulmacasıdır. Her tahminden sonra kareler renk değiştirerek ne kadar yaklaştığınızı gösterir: doğru yerdeki harf için yeşil, kelimede bulunan ama yanlış yerde olan harf için sarı ve kelimede hiç bulunmayan harf için gri. Her gün yepyeni bir bulmaca açılır ve herkes aynı kelimeyi oynar.",
  howToTitle: "Wordle nasıl oynanır",
  howToSteps: [
    { title: "İlk tahmininizi yazın", body: "Beş harfli geçerli herhangi bir kelime yazıp Enter'a basın. Tahmin etmenin cezası yok, bu yüzden ilk denemenizi yaygın harfleri test etmek için kullanın." },
    { title: "Renkleri okuyun", body: "Yeşil, harfin doğru ve doğru yerde olduğu anlamına gelir. Sarı, harfin kelimede olduğu ama başka bir yerde olduğu anlamına gelir. Gri, harfin kelimede olmadığı anlamına gelir." },
    { title: "Sonraki tahmininizi geliştirin", body: "Yeşil harfleri yerinde tutun, sarı harfleri yeni bir yere taşıyın ve sonraki tahminde gri harflerden tamamen kaçının." },
    { title: "Altı denemede çözün", body: "Gizli kelimeyi bulmak için altı tahmin hakkınız var. Her tahmin olasılıkları daraltır, bu yüzden onaylamadan önce düşünün." },
    { title: "Yarın tekrar gelin", body: "Günlük kelime gece yarısı sıfırlanır. Renkli ızgaranızı arkadaşlarınızla paylaşın ve cevabı bozmadan kaç deneme aldığınızı karşılaştırın." },
  ],
  moreGamesTitle: "Daha fazla kelime oyunu",
  moreGames: [
    { path: "/unlimited", name: "Sınırsız", thumb: "wordle", blurb: "İstediğiniz kadar rastgele bulmaca oynayın, günlük sınır yok." },
    { path: "/dordle", name: "Dordle", thumb: "dordle", blurb: "İki tahtayı paralel olarak yedi tahminde çözün." },
    { path: "/quordle", name: "Quordle", thumb: "quordle", blurb: "Dört tahtayı paralel olarak dokuz tahminde çözün." },
    { path: "/octordle", name: "Octordle", thumb: "octordle", blurb: "Sekiz tahtayı paralel olarak on üç tahminde çözün." },
    { path: "/sedecordle", name: "Sedecordle", thumb: "sedecordle", blurb: "On altı tahtayı aynı anda yirmi bir tahminde çözün." },
    { path: "/spellbee", name: "SpellBee", thumb: "spellbee", blurb: "Yedi harften olabildiğince çok kelime oluşturun." },
    { path: "/connect", name: "Bağla", thumb: "connect", blurb: "On altı kelimeyi dörderlik dört gizli gruba ayırın." },
    { path: "/squares", name: "Kareler", thumb: "squares", blurb: "4×4 ızgarada bitişik harfleri birleştirerek kelime oluşturun." },
    { path: "/custom", name: "Özel Kelime", thumb: "custom", blurb: "Kendi kelimenizi gizleyin ve bağlantıyı arkadaşlarınızla paylaşın." },
    { path: "/multiplayer", name: "Çok Oyunculu", thumb: "multiplayer", blurb: "Özel bir odada bir arkadaşınızla gerçek zamanlı yarışın." },
    { path: "/solver", name: "Çözücü", thumb: "solver", blurb: "Takıldınız mı? İpuçlarınızı girin ve tüm olası cevapları görün." },
    { path: "/archive", name: "Arşiv", thumb: "archive", blurb: "Kaçırdığınız geçmiş günlük bulmacaları tekrar oynayın." },
  ],
  languageTitle: "Bir dil seçin",
  languageIntro:
    "Wordle birçok dilde mevcuttur. Her sürümün kendi sözlüğü ve klavye düzeni vardır; en iyi bildiğiniz dilde oynayabilirsiniz.",
  tipsTitle: "Wordle oynamak için ipuçları",
  tips: [
    { title: "Güçlü bir kelimeyle başlayın", body: "Birkaç yaygın harfi kapsayan bir kelime seçin — sesli harfler ve sık ünsüzlerin dengeli karışımı tek bir tahminden en fazla bilgiyi verir." },
    { title: "Konuma dikkat edin", body: "Sarı bir kare, harfin kelimede olduğunu ama yerleştirdiğiniz yerde olmadığını söyler. Bir sonrakinde farklı bir yer deneyin ve aklınızda tutun." },
    { title: "Gri harfleri tekrar kullanmayın", body: "Bir harf gri olduğunda onu tamamen elemişsinizdir. İçeren bir kelimeye tahmin harcamak yalnızca sıra kaybetmektir." },
    { title: "Harf desenlerini arayın", body: "Her dilin yinelenen biçimleri vardır — yaygın son ekler, alışılmış ön ekler — ve bunları fark etmek genellikle son kareleri yerine kilitler." },
    { title: "Tanıdık kelimeleri deneyin", body: "Birden fazla harf uyduğunda günlük kelimelere yönelin. Cevap neredeyse hiçbir zaman belirsiz değildir." },
    { title: "Erken harf gruplarını eleyin", body: "İkinci veya üçüncü tahmininizi turu kazanamayacak olsanız bile yeni harfleri test etmek için kullanın. Beş harf daha elemek genellikle değer." },
    { title: "Sakin kalın ve düşünün", body: "Saat yok. Son iki tahminde yavaşlayın ve onaylamadan önce kalan adayları aklınızdan geçirin." },
    { title: "Çözücüyü idareli kullanın", body: "Çözücü öğrenmek için harikadır, ama her gün kullanmak tadını alır. Gerçekten takıldığınızda yedek olarak saklayın." },
    { title: "Düzenli olarak pratik yapın", body: "Ne kadar çok bulmaca oynarsanız desenler o kadar tanıdık gelir. Becerinizi korumak için günlük kısa bir tur yeterlidir." },
  ],
  faqTitle: "Sık sorulan sorular",
  faq: [
    { q: "Kaç tahmin hakkım var?", a: "Gizli kelimeyi bulmak için altı tahmin hakkınız vardır. Her tahmin doğru uzunlukta gerçek bir kelime olmalıdır." },
    { q: "Renkler ne anlama gelir?", a: "Yeşil doğru konumdaki bir harfi, sarı kelimede olan ama farklı konumdaki bir harfi, gri ise kelimede olmayan bir harfi gösterir." },
    { q: "Her gün yeni bir kelime var mı?", a: "Evet. Günlük bulmaca herkese aynı kelimeyi verir ve gece yarısı değişir. Daha fazlasını isterseniz Sınırsız modu hiç bitmez." },
    { q: "Günde birden fazla oynayabilir miyim?", a: "Günlük kelime günde bir kez, ancak Sınırsız, kelime uzunluğu varyantları ve özel oyunlar istediğiniz kadar oynamanıza izin verir." },
    { q: "Cevapta harfler tekrarlanabilir mi?", a: "Evet. Gizli kelime aynı harfi birden fazla içerebilir, bu yüzden çift harfleri elemeyin." },
    { q: "Zor Mod nedir?", a: "Zor Modda, açıklanan her ipucu sonraki her tahminde kullanılmalıdır: yeşiller yerinde kalır ve sarılar bir yerde görünmek zorundadır." },
    { q: "Sonucumu nasıl paylaşırım?", a: "Bitirdikten sonra paylaş düğmesi kaç deneme aldığınızı gösteren spoilersız renkli karelerden oluşan bir ızgarayı kopyalar." },
    { q: "Diğer dillerde oynayabilir miyim?", a: "Evet. Arayüzü ve kelime listesini desteklenen dillerden birine geçirmek için dil seçiciyi kullanın." },
  ],
  advantagesTitle: "Wordle oyununun avantajları",
  advantages: [
    { icon: "book", title: "Kelime dağarcığınızı geliştirir", body: "Her gün yeni kelimeleri tahmin etmek ve okumak, yazım ve kelime bilgisini almanın acısız bir yoludur." },
    { icon: "lightning", title: "Ücretsiz ve anında", body: "İndirme yok, kayıt yok, ödeme yok. Sayfayı açın ve hemen oynamaya başlayın." },
    { icon: "puzzle", title: "Mantığı keskinleştirir", body: "Her ipucu alanı daraltır. Cevabı bulmak küçük bir günlük tümdengelim egzersizidir." },
    { icon: "brain", title: "Hafif bir beyin egzersizi", body: "Birkaç odaklanmış dakikalık desen arama, iş gibi hissettirmeden zihni aktif tutar." },
    { icon: "clock", title: "Zaman baskısı yok", body: "Saat yok. Her tahmini düşünmek için istediğiniz kadar zaman alın." },
    { icon: "share", title: "Paylaşması eğlenceli", body: "Renkli ızgaranızı arkadaş ve aileyle karşılaştırın ve en az denemede kimin çözdüğüne bakın." },
  ],
  ratingTitle: "Oyunu puanlayın",
  ratingValue: 4.3,
  ratingCount: 3847,
};
